name: Drupal Code Quality
on: [pull_request]
jobs:
  Drupal-Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: cd ${{ github.workspace }}
      - name: Load Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          version: 2
      - name: Test codebase with grumPHP
        run: ./vendor/bin/grumphp run
