name: Drupal Code Quality
on: [ push ]
jobs:
  Drupal-Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo ":tada: The job was automatically triggered by a ${{ github.event_name }} event."
      - run:
          echo ":penguin: This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run:
          echo ":mag_right: The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run:
          echo ":bulb: The ${{ github.repository }} repository has been cloned to the runner."
      - run:
          echo ":desktop_computer: The workflow is now ready to test your code on the runner."
      - name: Test Codebase with grumPHP
      - run: cd ${{ github.workspace }}
      - run: ./vendor/bin/grumphp  run
      - run:
          echo ":green_apple: This job's status is ${{ job.status }}."

